version: "3"

services:
  web:
    image: jmalloc/echo-server
    networks:
      - mynetwork
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    networks:
      - mynetwork
    volumes:
      - "./config:/usr/local/etc/haproxy:ro"
    ports:
      - "80:80"
      - "8404:8404"
    depends_on:
      - web
networks:
  mynetwork: