version: "3"

services:
  web1:
    container_name: web1
    image: jmalloc/echo-server
    networks:
      - mynetwork
  web2:
    container_name: web2
    image: jmalloc/echo-server
    networks:
      - mynetwork
  web3:
    container_name: web3
    image: jmalloc/echo-server
    networks:
      - mynetwork
  haproxy:
    container_name: haproxy
    image: haproxytech/haproxy-alpine:2.4
    networks:
      - mynetwork
    volumes:
      - "./config:/usr/local/etc/haproxy:ro"
    ports:
      - "80:80"
      - "8404:8404"
    depends_on:
      - web1
      - web2
      - web3
networks:
  mynetwork: